### ISSUE TITLE
Chýbajúci label / názov moznosti platby a moznosti dodania

### ISSUE THREAD

**Issue by ladislavP** [beat-it/01-jsf#3]
Prosím o doplnenie položky name alebo label k GET /cart/delivery a k GET /cart/payment

**Comment by fpt-nessian** [comment]
ten name alebo label myslis do requestu alebo do response DTO?

momentalne to vyzera takto:

Request method:	GET
Request path:	http://localhost:8080/service/cart/delivery
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Multiparts:		<none>
Headers:		Authorization=Bearer tlmioavhpbinaa7qn1c1ndqtoq
				Accept=*/*
Cookies:		<none>
Body:			<none>
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Date: Mon, 28 Nov 2016 18:48:54 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Authorization: Bearer tlmioavhpbinaa7qn1c1ndqtoq
Content-Type: application/json
Content-Length: 97
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Max-Age: -1

[
    {
        "id": "KURIER",
        "price": 2.5,
        "currency": "EUR"
    },
    {
        "id": "OSOBNY_ODBER",
        "price": 0.0,
        "currency": "EUR"
    }
]

**Comment by ladislavP** [comment]
Doplnil by som nieco taketo: 
{
"id": "KURIER",
"price": 2.5,
"currency": "EUR",
"label": "Osobný odber"
},

nech tam nie su podcierkovniky

**Comment by ladislavP** [comment]
Resolvnute v https://github.com/beat-it/01-jsf/pull/8

**Comment by fpt-nessian** [comment]
Cize mozem zavret?

**Comment by ladislavP** [comment]
Ano ak aceeptnes pull request.

**Comment by fpt-nessian** [comment]
Hotovo:)
