### ISSUE TITLE
GET /cart

### ISSUE THREAD

**Issue by ladislavP** [beat-it/01-jsf#5]
GET /cart a PUT /cart nepoužívajú jednotné JSONs.

GET /cart vracia: 
payment: null, person: null, billingDetails: null, address: null

Zatiaľ, čo PUT /cart body je:
"billingAddress", "address", "person", "deliveryType", "paymentMethod"

Navyše aký je rozdiel medzi address a billingDetails? Address predstavuje adresu dodania a billingDetails sú fakturačné údaje aj s adresou?

Ďakujem.

**Comment by fpt-nessian** [comment]
Ahoj pridam endpointy na ulozenie Delivery a Payment. PUT /cart je len na akoby finalne vytvorenie objednavky, a v nej idu payment, billingDetails a adress atd. 

Veci sa pridavaju do kosika cez POST cart/items.

BillingDetails je adresa + company.

Pripadne ak mas na mysli nejake vhodnejsie riesenie, napis, skusim tam nahodit.

**Comment by ladislavP** [comment]
Neviem za mna by asi bolo lepsie mat len jeden endpoint `PUT /cart` na ktoru mozem zasla _t parcialnu zmenu kosika_ po prvom kroku delivery a payment po druhom data tykajuce sa osoby a adries. Finalne dkoncenie objednavke je v zasade aspon teraz nepotrebne.  Toto riesenie som popisal aj v dokumentacii.

**Comment by ladislavP** [comment]
Myslim ze toto mozeme uzavriet popis som presunul spolu do tejto chyby: https://github.com/beat-it/01-jsf/issues/10
